### ISSUE TITLE
Lots of code duplication

### ISSUE THREAD

**Issue by Validark** [grilme99/RobloxPlayFabSDK#3]
All the files I checked which end in `API.ts` have the same code over and over. This should be condensed in some way.

For AdminAPI.ts, for example, something like this could be used:

```ts
/// <reference path="AdminApiTypes.d.ts" />

import MakeRequest from './HTTP'
import Settings from './Settings'

const MakeRequestType = <T extends object, Q extends object>(requestPath: string) => async (request: T) => await MakeRequest<EmptyResponse>(requestPath, request, 'X-SecretKey', Settings.settings.secretKey || error('Must have Settings.settings.secretKey set to call this method')) as Q

/**
 * Abort an ongoing task instance.
 * https://docs.microsoft.com/rest/api/playfab/admin/scheduledtask/aborttaskinstance
 */
export const AbortTaskInstance = MakeRequestType<AbortTaskInstanceRequest, EmptyResponse>('/Admin/AbortTaskInstance');

/**
 * Update news item to include localized version
 * https://docs.microsoft.com/rest/api/playfab/admin/title-wide-data-management/addlocalizednews
 */
export const AddLocalizedNews = MakeRequestType<AddLocalizedNewsRequest, AddLocalizedNewsResult>('/Admin/AddLocalizedNews')
```

Even this would only be a basic improvement. If I had written this library, I would have transformed a literal array containing `["AbortTaskInstance", "AbortTaskInstance"]` into all the functions needed, and I would have defined the Request/Result table types in a lookup table so they can be dynamically accessed the first time when generating the type to export.

**Comment by Validark** [comment]
Also, if you like, you can use this regular expression to parse the AdminAPI.ts file. I wrote it anyway so I figured I'd drop it here if it saves you any time.

```
async \(request: (\s*\w+\s*)\) => \{\n\s*if \(!Settings\.settings\.secretKey\) throw 'Must have Settings\.settings\.secretKey set to call this method'\n\s*const result = await MakeRequest<(\w+)>\('([^']+)', request, 'X-SecretKey', Settings\.settings\.secretKey\)\n\s*return result\n\s*\}
```

To transform to the above form, you'd do:
```
MakeRequestType<$1, $2>('$3')
```

**Comment by BrookenRecord** [comment]
Hey! Thanks for bringing up the issue and sorry for the late response.

This will be improved upon in the refactor branch soon. It should be noted that in the refactor that I am working on each file will be generated automatically by the [PlayFab SDK Generator](https://github.com/PlayFab/SDKGenerator), Using this method updates will scale a lot better and be a lot easier to complete, only requiring you to edit one or two template files.

**Comment by BrookenRecord** [comment]
The refactor has now complete!
